POST http://localhost:4000/graphql? HTTP/1.1
content-type: application/json

{
  "query": "{\n  searchType(type:\"airport\", num:4){\n    ... on Airport{\n      airportname\n      country\n    }\n  }\n}",
  "variables": null,
  "operationName": null
}
